### ISSUE TITLE
CI fails due to brew traceback

### ISSUE THREAD

**Issue by rainest** [Kong/homebrew-deck#2]
CI is currently failing due to a traceback in brew itself:

```
Error: undefined method `audit_exceptions' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:159:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:148:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:148:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
The command "brew audit ./Formula/*.rb" exited with 1.
```
E.g. as seen in https://travis-ci.com/github/Kong/homebrew-deck/builds/202849221

This does not prevent us from actually updating the Homebrew files, but it prevents us from validating them. Release artifacts are already created by Goreleaser in the deck repo, and we have no reason to believe that the generated Homebrew files would actually be incorrect.

https://github.com/Homebrew/brew/commit/c784d9b9556e3cd3f3ebdc76957e27c5115ece0c looks like it likely fixes this (no details or example traceback, but isn't released as of yet. We should attempt to run again once a new release is available.

**Comment by hbagdi** [comment]
@rainest I pushed up https://github.com/hbagdi/homebrew-deck/runs/1480779674 to resolve https://github.com/Kong/deck/issues/236 and it seems to pass.

**Comment by rainest** [comment]
Homebrew 2.6.0 includes fix and the issue is gone. Hurray!
